import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated } = getKindeServerSession();

  const isLogedIn = await isAuthenticated();
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div className="md:px-20 xxl:mx-auto xxl:max-w-screen-2xl">
          <Header isLogedIn={isLogedIn} />
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
